SET SERVEROUTPUT ON
SET VERIFY OFF

VARIABLE LNAME VARCHAR2(225);
VARIABLE PNUM VARCHAR2(25);
VARIABLE ZIP VARCHAR2(25);

CREATE OR REPLACE PROCEDURE find_stud
(
STUD_ID IN NUMBER,
LASTNAME OUT VARCHAR2,
PHONENUM OUT VARCHAR2,
ZIPZ OUT VARCHAR2
)
IS
V_STUDID NUMBER;
BEGIN

SELECT ZIP INTO ZIPZ FROM STUDENT WHERE STUDENT_ID = STUD_ID;
SELECT LAST_NAME INTO LASTNAME FROM STUDENT WHERE STUDENT_ID = STUD_ID;
SELECT PHONE INTO PHONENUM FROM STUDENT WHERE STUDENT_ID = STUD_ID;
SELECT STUDENT_ID INTO V_STUDID FROM STUDENT WHERE STUDENT_ID = STUD_ID;

DBMS_OUTPUT.PUT_LINE('Student with the Id of: '||STUD_ID||' is '||LASTNAME||' with the phone# '||PHONENUM||' and who belongs to zip code '||ZIPZ);

EXCEPTION
WHEN NO_DATA_FOUND THEN
	DBMS_OUTPUT.PUT_LINE('There is NO Student with the Id of: '||V_STUDID);
END;
/

EXECUTE find_stud(110, :LNAME, :PNUM, :ZIP);
PRINT :LNAME;
PRINT :PNUM;
PRINT :ZIP;