DECLARE
v_Id NUMBER;
v_LName studentbld.LAST_NAME%TYPE;
BEGIN
SELECT STUDENT.LAST_NAME INTO v_LName
FROM STUDENT
INNER JOIN ENROLLMENT ON STUDENT.STUDENT_ID = ENROLLMENT.STUDENT_ID
WHERE LEN(LAST_NAME) > 9 AND STUDENT.STUDENT_ID = ENROLLMENT.STUDENT_ID
GROUP BY LAST_NAME
ORDER BY COUNT(STUDENT.LAST_NAME) DESC
LIMIT 1;

DBMS_OUTPUT.PUT_LINE('Student enrolled the most and with less than 9 chars: '||v_LName)

END;
/
