#!/bin/bash

if [ $# -lt 2 ]
then
	echo -n "You must give at least 2 arguments "
	exit
fi

echo -n "Enter your username : "

read username

add=0

for sum in $*
do
	let add=$add+$sum
done

echo "Your username is $username and the total is $add"
