all : rof5 test-move boolean-ops boolean-ops-long

rof5 : rof5.cpp
	g++ -std=c++0x -Wall rof5.cpp       -o rof5

test-move : test-move.cpp
	g++ -std=c++0x -Wall test-move.cpp  -o test-move

boolean-ops : boolean-ops.cpp
	g++ -std=c++0x -Wall boolean-ops.cpp  -o boolean-ops

boolean-ops-long : boolean-ops-long.cpp
	g++ -std=c++0x -Wall boolean-ops-long.cpp  -o boolean-ops-long
